### ISSUE TITLE
Complete todo

### ISSUE THREAD

**Issue by dgsunesen** [uryyyyyyy/react-redux-sample#6]
Hi,

Could you make an example of a complete todo action/reducer?

I've tried the following: 

`const completeTodo = (state: TodoState, action: MyAction): TodoState => {
    return state.todos.map(todo =>
      todo.id === action.id ?
        objectAssign({}, todo, { isComplete: !todo.isComplete }) :
        todo
    ); 
  }`

But I keep getting this error:

`Type 'Iterable<number, any>' is not assignable to type 'TodoState'.
  Property 'todos' is missing in type 'Iterable<number, any>'.`

Thanks.

**Comment by uryyyyyyy** [comment]
sorry for the late reply.
I will update samples soon.

(If you watch this repo and have question, please tell me the branch name.)
